### PR TITLE
Removed table row minimum size restriction on Book View and Time and …

### PR DESCRIPTION
**Pull request by spireken**
…Sales windows

### CODE REVIEW

**Comment by kranar** [comment]
The demo's don't show a difference between the two.

**Comment by spireken** [comment]
The old ones and new ones should look the same. I just fixed the issue where Qt was setting a minimum size for the rows.

**Comment by spireken** [comment]
Sorry, the builds for this branch are just called ..._qt5121. I only labelled the ones for fb1466.

**Comment by kranar** [comment]
Which demo's should I be comparing to ensure that this is fixed?

**Comment by spireken** [comment]
book_view_ui_tester and book_view_ui_tester_qt5121

**Comment by kranar** [comment]
Good job.

**Pull request merged**
