### PR TITLE
Fb1287

### PR DESCRIPTION
**Pull request by spireken**
I put a new Book View tester up on Dropbox. I temporarily changed the increase in volume to 10M so you can see the change on the technicals panel.

I also tested this with fractional values and it's working correctly.

### CODE REVIEW

**Comment by spireken** [comment]
I tried using this but the 'f' flag by itself gives me trailing zeros when the number is displayed, and the 'g' flag gives me the same output as the default flag, 'e'.

I can use the 'f' flag with a precision of 0, but then this won't work for fractional shares.

**Comment by kranar** [comment]
Okay good stuff, I will review this later.

**Comment by spireken** [comment]
Should I fix this conflict on my end and re-submit this?

**Comment by kranar** [comment]
No this case has been resolved and closed.

**Comment by spireken** [comment]
So just delete my local branch?

**Comment by kranar** [comment]
Yep, this case is now closed.

**Pull request closed without merging**
